name: Build Mac

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5
        pip install py2exe
    - name: Run Mac build
      run: |
        cd ${{ github.workspace }}
        ./build_mac.sh
    - name: Show build results
      run: |
        ls ${{ github.workspace }}/build/mac
        ls ${{ github.workspace }}/build/dist
